version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./data/db/:/app/data/db
  app:
    container_name: app
    build: .
    command: python3 run.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - app.env
