version: "3.9"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db_exporter:
    container_name: db_exporter
    image:  quay.io/prometheuscommunity/postgres-exporter
    networks:
      - back-tier
    ports:
      - 9187:9187
    env_file:
      - db_exporter.env

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - back-tier
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./data/db/:/app/data/db
    networks:
      - back-tier

  app:
    container_name: app
    build: .
    entrypoint: >
      sh -c "pip3 install -r requirements.txt &&
             python3 run.py"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - app.env
    networks:
      - back-tier
      - front-tier
